name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  nixfmt:
    name: nixfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Nix
        uses: cachix/install-nix-action@7ec16f2c061ab07b235a7245e06ed46fe9a1cab6 # v31.8.3

      - name: nixfmt
        run: nix run nixpkgs#nixfmt-rfc-style -- --check .

  deadnix:
    name: deadnix
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Nix
        uses: cachix/install-nix-action@7ec16f2c061ab07b235a7245e06ed46fe9a1cab6 # v31.8.3

      - name: deadnix
        run: nix run nixpkgs#deadnix -- --fail .

  show:
    name: nix flake show
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Nix
        uses: cachix/install-nix-action@7ec16f2c061ab07b235a7245e06ed46fe9a1cab6 # v31.8.3

      - name: Show flake structure
        run: nix flake show 2> /dev/null

  eval:
    name: nix flake check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Nix
        uses: cachix/install-nix-action@7ec16f2c061ab07b235a7245e06ed46fe9a1cab6 # v31.8.3

      - name: Check flake
        run: nix flake check
